# Generated by Django 5.2.15 on 2026-06-20 11:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctoravailability_doctorleave'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctorleave',
            options={'ordering': ['-start_leave_date']},
        ),
        migrations.RemoveConstraint(
            model_name='doctorleave',
            name='unique_doctor_leave_date',
        ),
        migrations.RenameField(
            model_name='doctorleave',
            old_name='leave_date',
            new_name='end_leave_date',
        ),
        migrations.AddField(
            model_name='doctorleave',
            name='start_leave_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='doctorleave',
            constraint=models.UniqueConstraint(fields=('doctor', 'start_leave_date', 'end_leave_date'), name='unique_doctor_leave_date'),
        ),
    ]
